#!/bin/bash
mkdir -p ~/.vim/autoload ~/.vim/bundle &&
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim &&
git clone https://github.com/vim-scripts/AutoComplPop &&
git clone https://github.com/mattn/emmet-vim &&
git clone https://github.com/bling/vim-airline &&
git clone https://github.com/jwalton512/vim-blade &&
git clone https://github.com/tpope/vim-commentary &&
git clone https://github.com/posva/vim-vue &&
git clone https://github.com/scrooloose/nerdtree &&
sudo apt-get install vim-gtk -y
