#!/bin/bash
if [[ -n $(dpkg -l | grep 'curl') ]];then
    sudo apt install curl -y
fi
if [[ -n $(dpkg -l | grep 'vim-gtk') ]];then
    sudo apt-get install vim-gtk -y
fi
vimDir=./vim
if [[ !(-e $vimDir) ]]; then
    mkdir $vimDir
fi

if [[ !(-e $vimDir/autoload) ]];then
    mkdir $vimDir/autoload
fi

if [[ !(-e $vimDir/autoload/pathogen.vim) ]];then
    curl -LSso  $vimDir/autoload/pathogen.vim https://tpo.pe/pathogen.vim 
fi

if [[ !(-e $vimDir/bundle) ]];then
    mkdir $vimDir/bundle
fi

#添加插件
cd $vimDir/bundle
if [[ !(-e $vimDir/bundle/AutoComplPop) ]];then
    git clone https://github.com/vim-scripts/AutoComplPop 
fi


if [[ !(-e $vimDir/bundle/emmet-vim) ]];then
    git clone https://github.com/mattn/emmet-vim 
fi

if [[ !(-e $vimDir/bundle/vim-airline) ]];then
    git clone https://github.com/bling/vim-airline 
fi

if [[ !(-e $vimDir/bundle/vim-blade) ]];then
    git clone https://github.com/jwalton512/vim-blade 
fi

if [[ !(-e $vimDir/bundle/vim-commentary) ]];then
    git clone https://github.com/tpope/vim-commentary 
fi

if [[ !(-e $vimDir/bundle/vim-vue) ]];then
    git clone https://github.com/posva/vim-vue 
fi

if [[ !(-e $vimDir/bundle/nerdtree) ]];then
    git clone https://github.com/scrooloose/nerdtree 
fi
